// Logros — datos extraidos de la wiki (resumido)
export const LOGROS = {
  "Armonia con la Brisa": { categoria: "Observacion de Aves", requisito: "Activa 100 Oleadas de Pajaros en total durante los Eventos de Observacion de Aves.", titulo: "Resonancia", nota: "Participa en Eventos con mas personas." },
  "Artista de Rompecabezas": { categoria: "General", requisito: "Maximiza el Sueno de Rompecabezas.", titulo: "Rompecabezas", nota: "Compra nuevos rompecabezas de Ka Ching." },
  "Atractor Humano de Insectos": { categoria: "Caza de Insectos", requisito: "Activa cuatro Enjambres en un unico Evento de Captura de Insectos.", titulo: "Atractor de Insectos", nota: "Participa con mas personas." },
  "Bendicion de los Cardumenes": { categoria: "Pesca", requisito: "Activa 100 Cardumenes a lo largo de multiples Eventos de Pesca.", titulo: "Bendicion", nota: "Organiza o participa en Eventos de Pesca con mas personas." },
  "Bendicion de los Cinco Insectos": { categoria: "Caza de Insectos", requisito: "Captura cinco insectos de 5 Estrellas durante un unico Evento.", titulo: "Senor de los Insectos", nota: "Aumenta tu nivel del Hobby." },
  "Cantina Miau-Miau": { categoria: "Cuidado de Gatos", requisito: "Alimenta a cinco Gatos con su comida favorita.", titulo: "Comida para Gatos", nota: "Evita la comida estandar." },
  "Cantina Perruna": { categoria: "Cuidado de Perros", requisito: "Alimenta a tres Perros con su comida favorita.", titulo: "Comida para Perros", nota: "Usa comida favorita." },
  "CD de Musica Dorado": { categoria: "General", requisito: "Maximiza el Sueno de Musico.", titulo: "Musica", nota: "Toca, Graba y Publica Musica." },
  "Coleccionista": { categoria: "General", requisito: "Conviertete en Coleccionista Experto.", titulo: "Coleccionista", nota: "Es el rango mas alto del medidor." },
  "Coleccionista de Polvo de Estrellas": { categoria: "General", requisito: "Recoge 60 Fragmentos de Estrellas Fugaces.", titulo: "Recolector de Estrellas", nota: "Recogelos durante Lluvias de Meteoros." },
  "Comandante de Insectos": { categoria: "Caza de Insectos", requisito: "Alcanza el Nivel 10 del Hobby de Captura de Insectos.", titulo: "Maestro de Insectos", nota: "Captura diariamente y participa en eventos." },
  "Cosecha Abundante": { categoria: "Jardineria", requisito: "Cosecha cultivos de 5 Estrellas mientras la Cosecha Bonus esta activa.", titulo: "Cosecha", nota: "Ocurre durante clima de Arcoiris." },
  "Cuidador de Animales": { categoria: "General", requisito: "Descubre la comida favorita de los ocho grupos de animales.", titulo: "Delicioso", nota: "Prueba varios items." },
  "Entrenador de Perros Experto": { categoria: "Cuidado de Perros", requisito: "Alcanza el Nivel 10 en el Hobby de Cuidado de Perros.", titulo: "Companero de Perros", nota: "Alimenta, entrena y juega cada dia." },
  "Fortuna del Pez Gemelo": { categoria: "Pesca", requisito: "Atrapa dos peces de 5 Estrellas en un minuto.", titulo: "Aguila Pescadora", nota: "Mas facil durante Eventos de Pesca." },
  "Leyenda Culinaria del Pueblo": { categoria: "Cocina", requisito: "Alcanza el Nivel 10 en el Hobby de Cocina.", titulo: "Chef", nota: "Experimenta con ingredientes y cocina rapido." },
  "Maquina de Pescar": { categoria: "Pesca", requisito: "Atrapa 50 peces que pesen mas de 100 kg cada uno.", titulo: "Cesta de Peces", nota: "Es acumulativo." },
  "Nunca con las Manos Vacias": { categoria: "Pesca", requisito: "Alcanza el Nivel 10 del Hobby de Pesca.", titulo: "Pescador Habil", nota: "Participa en Eventos de Pesca." },
  "Patrocinador del Cohete": { categoria: "General", requisito: "Gana 500,000 Oro vendiendo articulos a Albert Jr.", titulo: "Cohete", nota: "Vende artículos de alto valor." },
  "Pluma Persistente": { categoria: "General", requisito: "Maximiza el Sueno de Escritura.", titulo: "Escritura", nota: "Escribe libros y publicalos." },
  "Rapido e Impecable": { categoria: "Cocina", requisito: "Cocina dos platos de 5 Estrellas en 60 segundos.", titulo: "Reloj de Cocina", nota: "Aumenta tu nivel de Cocina." },
  "Sirviente de Gatos Experto": { categoria: "Cuidado de Gatos", requisito: "Alcanza el Nivel 10 en el Hobby de Cuidado de Gatos.", titulo: "Amante de los Gatos", nota: "Alimenta y juega cada dia." },
  "Susurrador de Pajaros": { categoria: "Observacion de Aves", requisito: "Alcanza el Nivel 10 del Hobby de Observacion de Aves.", titulo: "Susurrador de Pajaros", nota: "Participa en Eventos." },
  "Toque Verde": { categoria: "Jardineria", requisito: "Alcanza el Nivel 10 en el Hobby de Jardineria.", titulo: "Horticultor", nota: "Cosecha y replanta inmediatamente." },
  "Vecino Animal": { categoria: "General", requisito: "Alcanza el Nivel 10 con ocho grupos de animales diferentes.", titulo: "Nuevo Vecino", nota: "Llena el Comedero con comida favorita." },
};
