// Aves — datos extraidos de la wiki
export const AVES = {
  "Paloma de Oliva Africana": { ubicacion: "Montana Onsen (Onsen)", nivel: 5, actividad: "Diaria", clima: ["Soleado", "Lluvioso", "Arcoiris"], horario: ["Noche", "Amanecer", "Dia", "Atardecer"] },
  "Flamenco Americano": { ubicacion: "Campo de Flores", nivel: 9, actividad: "Diaria", clima: ["Arcoiris"], horario: ["Dia"] },
  "Gaviota de Audouin": { ubicacion: "Mar Ballena, Playa Amatista", nivel: 3, actividad: "Diaria", clima: ["Soleado", "Lluvioso", "Arcoiris"], horario: ["Noche", "Amanecer", "Dia", "Atardecer"] },
  "Herrerillo Azur": { ubicacion: "Campo de Flores (Campo del Molino)", nivel: 7, actividad: "Diaria", clima: ["Soleado", "Lluvioso", "Arcoiris"], horario: ["Noche", "Amanecer", "Dia", "Atardecer"] },
  "Bigotudo": { ubicacion: "Montana Onsen", nivel: 2, actividad: "Diaria", clima: ["Soleado", "Lluvioso", "Arcoiris"], horario: ["Noche", "Amanecer", "Dia", "Atardecer"] },
  "Pavo Real Azul": { ubicacion: "Evento Nido de Cientos", nivel: 1, actividad: "Diaria", clima: ["Soleado", "Lluvioso", "Arcoiris"], horario: ["Noche", "Amanecer", "Dia", "Atardecer"] },
  "Guacamayo Azul y Amarillo": { ubicacion: "Evento Nido de Cientos", nivel: 1, actividad: "Diaria", clima: ["Soleado", "Lluvioso", "Arcoiris"], horario: ["Noche", "Amanecer", "Dia", "Atardecer"] },
  "Camachuelo Comun": { ubicacion: "Suburbios", nivel: 1, actividad: "Diaria", clima: ["Soleado", "Lluvioso", "Arcoiris"], horario: ["Noche", "Amanecer", "Dia", "Atardecer"] },
  "Pinzon Vulgar": { ubicacion: "Campo de Flores", nivel: 1, actividad: "Diaria", clima: ["Soleado", "Lluvioso", "Arcoiris"], horario: ["Noche", "Amanecer", "Dia", "Atardecer"] },
  "Tortola Turca": { ubicacion: "Hogar", nivel: 1, actividad: "Diaria", clima: ["Soleado", "Lluvioso", "Arcoiris"], horario: ["Noche", "Amanecer", "Dia", "Atardecer"] },
  "Oropendola Europea": { ubicacion: "Rio Rosado, Hogar", nivel: 3, actividad: "Diaria", clima: ["Soleado", "Lluvioso", "Arcoiris"], horario: ["Noche", "Amanecer", "Dia", "Atardecer"] },
  "Trepador Azul": { ubicacion: "Aldea de Pescadores", nivel: 2, actividad: "Diaria", clima: ["Soleado", "Lluvioso", "Arcoiris"], horario: ["Noche", "Amanecer", "Dia", "Atardecer"] },
  "Chochin Comun": { ubicacion: "Bosque", nivel: 1, actividad: "Diaria", clima: ["Soleado", "Lluvioso", "Arcoiris"], horario: ["Noche", "Amanecer", "Dia", "Atardecer"] },
  "Petirrojo Europeo": { ubicacion: "Area Central", nivel: 1, actividad: "Diaria", clima: ["Soleado", "Lluvioso", "Arcoiris"], horario: ["Noche", "Amanecer", "Dia", "Atardecer"] },
  "Flamenco Mayor": { ubicacion: "Orilla del Agua", nivel: 1, actividad: "Diaria", clima: ["Soleado", "Lluvioso", "Arcoiris"], horario: ["Noche", "Amanecer", "Dia", "Atardecer"] },
  "Anade Real": { ubicacion: "Lago", nivel: 1, actividad: "Diaria", clima: ["Soleado", "Lluvioso", "Arcoiris"], horario: ["Noche", "Amanecer", "Dia", "Atardecer"] },
  "Tangara Siete Colores": { ubicacion: "Suburbios", nivel: 9, actividad: "Diaria", clima: ["Soleado", "Lluvioso", "Arcoiris"], horario: ["Noche", "Amanecer", "Dia", "Atardecer"] },
  "Halcon Peregrino": { ubicacion: "Montana Onsen (Onsen)", nivel: 7, actividad: "Diaria", clima: ["Lluvioso", "Arcoiris"], horario: ["Noche", "Amanecer", "Dia", "Atardecer"] },
  "Cormorán Imperial": { ubicacion: "Mar del Este / Mar Cefiro", nivel: 9, actividad: "Diaria", clima: ["Soleado", "Lluvioso", "Arcoiris"], horario: ["Noche", "Amanecer", "Dia", "Atardecer"] },
  "Paloma Rosa": { ubicacion: "Campo de Flores (Montana Ballena)", nivel: 7, actividad: "Diaria", clima: ["Soleado", "Lluvioso", "Arcoiris"], horario: ["Noche", "Amanecer", "Dia", "Atardecer"] },
  "Paloma Zurita": { ubicacion: "Area Central", nivel: 1, actividad: "Diaria", clima: ["Soleado", "Lluvioso", "Arcoiris"], horario: ["Noche", "Amanecer", "Dia", "Atardecer"] },
  "Gaviota": { ubicacion: "Costa", nivel: 2, actividad: "Diaria", clima: ["Soleado", "Lluvioso", "Arcoiris"], horario: ["Noche", "Amanecer", "Dia", "Atardecer"] },
  "Azulejo de las Montanas": { ubicacion: "Suburbios", nivel: 8, actividad: "Diaria", clima: ["Lluvioso", "Arcoiris"], horario: ["Noche", "Amanecer", "Dia", "Atardecer"] },
  "Cernícalo Vulgar": { ubicacion: "Bosque (Torre del Ciervo)", nivel: 7, actividad: "Diaria", clima: ["Soleado", "Arcoiris"], horario: ["Noche", "Amanecer", "Dia", "Atardecer"] },
  "Malvasia Cabeciblanca": { ubicacion: "Montana Onsen (Orilla del Lago)", nivel: 9, actividad: "Diaria", clima: ["Lluvioso", "Arcoiris"], horario: ["Noche", "Amanecer", "Dia", "Atardecer"] },
};
